from datetime import datetime

# 基本設定
DEFAULT_NUM_WORKERS = 2
DEFAULT_WORKDAY_HOURS = 9
DEFAULT_START_DATE = datetime(2024, 12, 5, 9, 0)

# プロジェクト期間
PROJECT_START_DATE = '2024-12-01'
PROJECT_END_DATE = '2024-12-31'

# Excel関連
DEFAULT_EXCEL_FILENAME = 'WBS.xlsx'
DEFAULT_SHEET_NAME = 'Sheet1'